language: node_js

# before_install:

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run build

deploy:
  - cd frontend && npm run build
  - sudo systemctl restart node_env.service

git:
  depth: false

branches:
  only:
    - master
